### PR TITLE
deploy: add new deploy files

### PR DESCRIPTION
**Pull request by zanzipanziby**
add new deploy files for postravel.ru

### CODE REVIEW

**Comment by MrPapperlapapp** [comment]
run build production

**Comment by Svyat-1418** [comment]
run build production

**Review by Svyat-1418 — APPROVED** [review]

**Comment by Svyat-1418** [comment]
run build production

**Review by MrPapperlapapp — APPROVED** [review]

**Comment by Svyat-1418** [comment]
run build production

**Comment by MrPapperlapapp** [comment]
run build production

**Comment by IL-2602** [comment]
run build production

**Comment by IL-2602** [comment]
run build production

**Comment by IL-2602** [comment]
run build production

**Comment by IL-2602** [comment]
run build production

**Comment by MrPapperlapapp** [comment]
run build production

**Pull request merged**
